"""Add comleted flag to Note

Revision ID: 7f98835d08d6
Revises: d844093f2f8d
Create Date: 2025-07-18 05:30:50.632064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f98835d08d6'
down_revision: Union[str, Sequence[str], None] = 'd844093f2f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_completed')
    # ### end Alembic commands ###
